dashmachine/docs_system/routes.py
import os
from flask import render_template, Blueprint, redirect, request
from flask_login import current_user
from dashmachine.paths import root_folder, wiki_folder
from dashmachine.docs_system.core_docs import (
    settings_doc_dict,
    user_settings_doc_dict,
    apps_doc_dict,
    collections_doc_dict,
    custom_card_doc_dict,
    data_sources_doc_dicts,
    access_groups_doc_dict,
)
from dashmachine.docs_system.utils import (
    get_md_from_file,
    get_md_from_dict,
    get_toc_md_from_dicts,
    create_edit_wiki,
)
from dashmachine.moment import create_moment
from dashmachine.main.utils import get_apps_and_tags, get_access_group
from dashmachine.main.models import Wiki, WikiTags

docs_system = Blueprint("docs_system", __name__)


@docs_system.route("/docs_home", methods=["GET"])
def docs_home():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    apps, tags = get_apps_and_tags(access_group)
    if redirect_url:
        return redirect(redirect_url)
    return render_template(
        "docs_system/docs-home.html",
        about_html=get_md_from_file(os.path.join(root_folder, "README.md")),
        install_html=get_md_from_file("install.md"),
        getting_started_html=get_md_from_file("getting-started.md"),
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/docs_main_settings", methods=["GET"])
def docs_main_settings():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    return render_template(
        "docs_system/docs-main-settings.html",
        main_settings_html=get_md_from_dict(settings_doc_dict),
        user_settings_html=get_md_from_dict(user_settings_doc_dict),
        ag_settings_html=get_md_from_dict(access_groups_doc_dict),
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/docs_cards", methods=["GET"])
def docs_cards():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    return render_template(
        "docs_system/docs-cards.html",
        apps_html=get_md_from_dict(apps_doc_dict),
        collections_html=get_md_from_dict(collections_doc_dict),
        custom_cards_html=get_md_from_dict(custom_card_doc_dict),
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/docs_data_sources", methods=["GET"])
def docs_data_sources():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    doc_dicts = data_sources_doc_dicts(get_all=True)
    data_sources_html = get_toc_md_from_dicts(doc_dicts)
    for doc in doc_dicts:
        data_sources_html += f"\n\n{get_md_from_dict(doc)}"
    return render_template(
        "docs_system/docs-data-sources.html",
        data_sources_main_html=get_md_from_file("data-sources.md"),
        creating_platforms_html=get_md_from_file("creating-platforms.md"),
        platform_methods_html=get_md_from_file("platform-methods.md"),
        data_sources_html=data_sources_html,
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/wiki_tags", methods=["GET"])
def wiki_tags():
    access_group, redirect_url = get_access_group(current_user, page="wikis")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)

    wiki_tags_db = WikiTags.query.all()
    return render_template(
        "docs_system/wiki-tags.html",
        access_group=access_group,
        apps=apps,
        tags=tags,
        wiki_tags=wiki_tags_db,
    )


@docs_system.route("/wikis", methods=["GET"])
def wikis():
    access_group, redirect_url = get_access_group(current_user, page="wikis")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)

    if request.args.get("tag", None):
        tag = WikiTags.query.filter_by(id=request.args.get("tag")).first()
        wikis_db = tag.wikis
    else:
        tag = None
        wikis_db = Wiki.query.all()
    for wiki_db in wikis_db:
        wiki_db.updated_moment = create_moment(wiki_db.updated)
    return render_template(
        "docs_system/wikis.html",
        access_group=access_group,
        apps=apps,
        tags=tags,
        wikis=wikis_db,
        tag=tag,
    )


@docs_system.route("/wiki-<permalink>", methods=["GET"])
def wiki(permalink=None):
    access_group, redirect_url = get_access_group(current_user, page="wiki")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)

    wiki_db = Wiki.query.filter_by(permalink=permalink).first()
    if wiki_db:
        wiki_fp = os.path.join(wiki_folder, f"{wiki_db.name}.md")
        with open(wiki_fp, "r") as file:
            wiki_md = file.read()
        wiki_md_html = get_md_from_file(file=wiki_db.name, full_path=wiki_fp)
    else:
        wiki_md_html = None

    if wiki_db.wiki_tags.count() > 0:
        wiki_db.tags_str = ",".join([tag.name for tag in wiki_db.wiki_tags])
    return render_template(
        "docs_system/wiki.html",
        access_group=access_group,
        wiki=wiki_db,
        wiki_md_html=wiki_md_html,
        wiki_md=wiki_md,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/save_wiki", methods=["POST"])
def save_wiki():
    create_edit_wiki(
        permalink=request.form.get("wiki_permalink", None),
        permalink_new=request.form.get("wiki_permalink_new", None),
        name=request.form.get("wiki_name", None),
        author=request.form.get("wiki_author", None),
        description=request.form.get("wiki_description", None),
        md=request.form.get("config", None),
        tags=request.form.get("wiki_tags", None),
    )
    return "ok"

dashmachine/templates/docs_system/docs-base.html
{% extends "main/layout.html" %}

{% block page_vendor_css %}
{% endblock page_vendor_css %}

{% block page_lvl_css %}
        {{ process_css_sources(src="docs_system/docs-base.css")|safe }}
{% endblock page_lvl_css %}

{% block content %}
    {% block navbar %}{% endblock navbar %}

    <div id="main" class="main-full {% block main_class %}{% endblock main_class %}">
        <div id="md-container">
            {% block md_content %}{% endblock md_content %}
        </div>
    </div>
{% endblock content %}

{% block page_vendor_js %}
{% endblock page_vendor_js %}

{% block page_lvl_js %}
        {{ process_js_sources(src="docs_system/docs-base.js")|safe }}
{% endblock page_lvl_js %}

dashmachine/templates/docs_system/docs-cards.html
{% extends "docs_system/docs-layout.html" %}

{% block tabs %}
    <li class="tab"><a class="active" href="#cards-apps">Apps</a></li>
    <li class="tab"><a href="#cards-collection">Collections</a></li>
    <li class="tab"><a href="#cards-custom">Custom</a></li>
{% endblock tabs %}

{% block tabs_content %}
    <div id="cards-apps" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ apps_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="cards-collection" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ collections_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="cards-custom" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ custom_cards_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock tabs_content %}

dashmachine/templates/docs_system/docs-data-sources.html
{% extends "docs_system/docs-layout.html" %}

{% block tabs %}
    <li class="tab"><a class="active" href="#data-sources-main">Data Sources</a></li>
    <li class="tab"><a href="#data-sources-platforms">Platforms</a></li>
    <li class="tab"><a href="#data-sources-create">Creating Platforms</a></li>
    <li class="tab"><a href="#data-sources-methods">Platform Methods</a></li>
{% endblock tabs %}

{% block tabs_content %}
    <div id="data-sources-main" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ data_sources_main_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="data-sources-platforms" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ data_sources_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="data-sources-create" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ creating_platforms_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="data-sources-methods" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ platform_methods_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock tabs_content %}

dashmachine/templates/docs_system/docs-home.html
{% extends "docs_system/docs-layout.html" %}

{% block tabs %}
    <li class="tab"><a class="active" href="#setup-about">About</a></li>
    <li class="tab"><a href="#setup-installation">Installation</a></li>
    <li class="tab"><a href="#setup-getting-started">Getting Started</a></li>
{% endblock tabs %}

{% block tabs_content %}
    <div id="setup-about" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ about_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="setup-installation" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ install_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="setup-getting-started" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ getting_started_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock tabs_content %}

dashmachine/templates/docs_system/docs-layout.html
{% extends "docs_system/docs-base.html" %}
{% from 'global_macros.html' import DMLogo, button %}

{% macro NavItems() %}
    <li>
        {{ button(
        icon="check_circle",
        float="",
        href=url_for('docs_system.docs_home'),
        text="Setup"
        ) }}
    </li>
    <li>
        {{ button(
        icon="settings",
        float="",
        href=url_for('docs_system.docs_main_settings'),
        text="Settings"
        ) }}
    </li>
    <li>
        {{ button(
        icon="aspect_ratio",
        float="",
        href=url_for('docs_system.docs_cards'),
        text="Cards"
        ) }}
    </li>
    <li>
        {{ button(
        icon="language",
        float="",
        href=url_for('docs_system.docs_data_sources'),
        text="Data Sources"
        ) }}
    </li>
{% endmacro %}

{% block main_class %}mt-3 ml-1{% endblock main_class %}

{% block navbar %}
    <div class="navbar-fixed">
        <nav class="nav-extended theme-surface pl-1 z-depth-1" style="border-radius: 0 0 10px 10px">
            <div class="nav-wrapper">
                <a href="{{ url_for('docs_system.docs_home') }}" class="brand-logo right theme-primary-text">{{ DMLogo(size="32px", style="position: relative; top: 6px") }} Docs</a>

                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons-outlined theme-primary-text">menu</i></a>
                <ul id="nav-mobile" class="hide-on-med-and-down">
                    {{ NavItems() }}
                </ul>
            </div>
            <div class="nav-content">
                <ul class="tabs theme-surface" style="border-bottom-right-radius: 10px;">
                    {% block tabs %}{% endblock tabs %}
                </ul>
            </div>
        </nav>
    </div>

    <ul class="sidenav" id="mobile-demo" style="top: 110px">
        {{ NavItems() }}
    </ul>
{% endblock navbar %}

{% block md_content %}
    {% block tabs_content %}{% endblock tabs_content %}
{% endblock md_content %}

dashmachine/templates/docs_system/docs-main-settings.html
{% extends "docs_system/docs-layout.html" %}

{% block tabs %}
    <li class="tab"><a class="active" href="#main-settings">Main Settings</a></li>
    <li class="tab"><a href="#ag-settings">Access Groups</a></li>
    <li class="tab"><a href="#user-settings">User Settings</a></li>
{% endblock tabs %}

{% block tabs_content %}
    <div id="main-settings" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ main_settings_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="ag-settings" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ ag_settings_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="user-settings" class="col s12">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            {{ user_settings_html|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock tabs_content %}

dashmachine/templates/docs_system/wiki-tags.html
{% extends "main/layout.html" %}

{% block page_vendor_css %}
{% endblock page_vendor_css %}

{% block page_lvl_css %}
    {#    {{ process_css_sources(src="main/home.css")|safe }}#}
{% endblock page_lvl_css %}

{% block content %}
    <div id="main" class="main-full">
        <div class="container">
            <div class="row card-filter-container" style="padding-left: 10px">
                <div class="col s12 m12 l4 xl3  input-field">
                    <span>
                        <i class="material-icons prefix card-search-icon">search</i>
                        <input type="text" id="wiki-tags-search" class="card-filter theme-surface" placeholder="Search tags">
{#                        <i class="material-icons right filter-action pointer">language</i>#}
                    </span>
                </div>
            </div>

            <div class="row" style="padding-left: 10px">
                <div class="col s12">
                    <h4 class="theme-muted-text mb-0">Tags
                        <i class="material-icons-outlined icon-btn">add</i>
                    </h4>
                </div>
                {% for wiki_tag in wiki_tags %}
                    <div class="col s12 m12 l4 xl3">
                        <div class="card">
                            <a href="{{ url_for('docs_system.wikis', tag=wiki_tag.id) }}">
                                <div class="card-content">
                                    <span class="font-weight-900" style="font-size: 1.2rem">{{ wiki_tag.name }}</span>
                                </div>
                            </a>
                            <div class="card-action theme-primary theme-on-primary-text pt-1 pb-1">
                                <i class="material-icons-outlined icon-btn">edit</i>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block page_vendor_js %}
{% endblock page_vendor_js %}

{% block page_lvl_js %}
    {#    {{ process_js_sources(src="main/home.js")|safe }}#}
{% endblock page_lvl_js %}

dashmachine/templates/docs_system/wiki.html
{% extends "docs_system/docs-base.html" %}
{% block md_content %}
    <div class="row" style="padding-left: 8px;">
        <div class="col s12 l6 xl6 hide">
            <div class="card">
                <div class="card-content">
                    <h5>Wiki</h5>
                </div>
                <div class="card-action">
                    tags!
                </div>
            </div>
        </div>

        <div class="col s12">
            <div class="card">
                <div class="card-content theme-primary theme-on-primary-text" style="padding: 1rem">
                    <div class="row">
                        <div class="col s12 m6">
                            <span class="font-weight-900 theme-on-primary-text">{{ wiki.name }}</span><br>
                            <span class="theme-on-primary-text">{{ wiki.description }}</span>
                        </div>
                        <div class="col s12 m6 right-align">
                            <span class="theme-on-primary-text">
                                <i id="edit-wiki-btn"
                                   class="material-icons-outlined icon-btn"
                                   data-permalink="{{ wiki.permalink }}"
                                   data-name="{{ wiki.name }}"
                                   data-author="{{ wiki.author }}"
                                   data-description="{{ wiki.description }}"
                                   data-tags="{{ wiki.tags_str }}"
                                   data-md="{{ wiki_md }}">edit
                                </i>
                                <i class="material-icons-outlined icon-btn">delete</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="card-action">
                    {% if wiki %}
                        <div id="wiki-md-container">
                            {{ wiki_md_html|safe }}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
{% endblock md_content %}

{% block page_lvl_js %}
    {{ process_js_sources(src="docs_system/wiki.js")|safe }}
{% endblock page_lvl_js %}

dashmachine/templates/docs_system/wikis.html
{% extends "main/layout.html" %}

{% block page_vendor_css %}
{% endblock page_vendor_css %}

{% block page_lvl_css %}
{#    {{ process_css_sources(src="main/home.css")|safe }}#}
{% endblock page_lvl_css %}

{% block content %}
    <div id="main" class="main-full">
        <div class="container">
            <div class="row card-filter-container" style="padding-left: 10px">
                <div class="col s12 m12 l4 xl3  input-field">
                    <span>
                        <i class="material-icons prefix card-search-icon">search</i>
                        <input type="text" id="wikis-search" class="card-filter theme-surface" placeholder="Search wikis">
{#                        <i class="material-icons right filter-action pointer">language</i>#}
                    </span>
                </div>
            </div>

            <div class="row" style="padding-left: 10px">
                <div class="col s12">
                    <h4 class="theme-muted-text mb-0">{{ tag.name }}
                        <i class="material-icons-outlined icon-btn">add</i>
                    </h4>
                </div>
                {% for wiki in wikis %}
                    <div class="col s12 m12 l4 xl3">
                        <div class="card">
                            <a href="{{ url_for('docs_system.wiki', permalink=wiki.permalink) }}">
                                <div class="card-content">
                                    <span class="font-weight-900" style="font-size: 1.2rem">{{ wiki.name }}</span><br>
                                    <span class="theme-secondary-text">{{ wiki.description }}</span><br>
                                    <span> {{ wiki.updated_moment }}</span>
                                </div>
                            </a>
                            <div class="card-action theme-primary theme-on-primary-text pt-1 pb-1">
                                <i class="material-icons-outlined icon-btn">link</i>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block page_vendor_js %}
{% endblock page_vendor_js %}

{% block page_lvl_js %}
{#    {{ process_js_sources(src="main/home.js")|safe }}#}
{% endblock page_lvl_js %}