dashmachine/main/routes.py
import os
import glob
import json
from secrets import token_hex
from htmlmin.main import minify
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint,
    jsonify,
    render_template_string,
)
from flask_login import current_user
from dashmachine.main.models import Files, Apps, DataSources
from dashmachine.main.utils import (
    get_data_source,
    mark_update_message_read,
    row2dict,
    get_apps_and_tags,
    get_access_group,
    backup_working_config,
    get_template_apps,
)
from dashmachine.main.modify_config import modify_config
from dashmachine.settings_system.models import Settings
from dashmachine.settings_system.forms import ConfigForm
from dashmachine.settings_system.utils import load_files_html
from dashmachine.docs_system.utils import get_card_doc_dict
from dashmachine.docs_system.core_docs import (
    configured_data_sources_doc_dicts,
    settings_doc_dict,
    user_settings_doc_dict,
    access_groups_doc_dict,
    data_sources_doc_dicts,
)
from dashmachine.user_system.models import User, AccessGroups
from dashmachine.paths import cache_folder, user_data_folder
from dashmachine.version import version, revision_number
from dashmachine import app, db


main = Blueprint("main", __name__)


# ------------------------------------------------------------------------------
# intial routes and functions (before/after request)
# ------------------------------------------------------------------------------
@app.after_request
def response_minify(response):
    """
    minify html response to decrease site traffic
    """
    if response.content_type == "text/html; charset=utf-8":
        response.set_data(minify(response.get_data(as_text=True)))

        return response
    return response


# ------------------------------------------------------------------------------
# /home
# ------------------------------------------------------------------------------
@main.route("/")
@main.route("/home", methods=["GET"])
def home():
    access_group, redirect_url = get_access_group(current_user, page="home")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    return render_template(
        "main/home.html", apps=apps, tags=tags, access_group=access_group, page="home"
    )


# ------------------------------------------------------------------------------
# /home modules
# ------------------------------------------------------------------------------
@main.route("/load_apps", methods=["GET"])
def load_apps():
    access_group, redirect_url = get_access_group(current_user)
    apps, tags = get_apps_and_tags(access_group)

    if request.args.get("home", None) == "true":
        html = render_template_string(
            """
            {% from 'main/cards.html' import HomeCards %}
            {{ HomeCards(apps, tags) }}
            """,
            apps=apps,
            tags=tags,
        )
    elif request.args.get("sidenav", None) == "true":
        html = render_template_string(
            """
            {% from 'main/cards.html' import SidenavApps %}
            {{ SidenavApps(apps, tags) }}
            """,
            apps=apps,
            tags=tags,
        )
    return html


@main.route("/load_card_editor", methods=["GET"])
def load_card_editor():
    access_group, redirect_url = get_access_group(current_user)
    apps, tags = get_apps_and_tags(access_group)
    data_sources = []
    for ds in DataSources.query.all():
        data_sources.append({"id": ds.id, "name": ds.name, "platform": ds.platform})
    card_editor_html = render_template_string(
        """
        {% from 'main/card-editor.html' import CardEditor with context %}
        {{ CardEditor() }}
        """,
        data_sources=data_sources,
        apps=apps,
    )
    return card_editor_html


@main.route("/load_config_editor", methods=["GET"])
def load_config_editor():
    config_form = ConfigForm()
    with open(os.path.join(user_data_folder, "config.ini"), "r") as config_file:
        config_form.config.data = config_file.read()
    config_editor_html = render_template_string(
        """
        {% from 'main/config-editor.html' import ConfigEditor with context %}
        {{ ConfigEditor() }}
        """,
        config_form=config_form,
    )
    return config_editor_html


@main.route("/load_settings_editor", methods=["GET"])
def load_settings_editor():
    settings_db = Settings.query.first()
    files_html = load_files_html()
    access_group, redirect_url = get_access_group(current_user)

    access_groups = AccessGroups.query.all()
    users = User.query.all()

    # GUI DICTS
    user_dicts = [row2dict(user) for user in User.query.all()]
    for user_dict in user_dicts:
        user_dict["password"] = None
    user_settings_doc_dict["docs_url"] = url_for(
        "docs_system.docs_main_settings", _anchor="user-settings"
    )
    settings_dict = row2dict(settings_db)
    settings_doc_dict["docs_url"] = url_for("docs_system.docs_main_settings")
    settings_dict["action_providers"] = ["list"] + [
        json.loads(tag_json)
        for tag_json in settings_dict["action_providers"]
        .replace("},{", "}%,%{")
        .split("%,%")
    ]
    if settings_dict.get("tags", "None") != "None":
        settings_dict["tags"] = ["list"] + [
            json.loads(tag_json)
            for tag_json in settings_dict["tags"].replace("},{", "}%,%{").split("%,%")
        ]
    else:
        settings_dict["tags"] = ["list"] + [{"name": "", "icon": "", "sort_pos": ""}]
    settings_editor_html = render_template_string(
        """
        {% from 'main/settings-editor.html' import SettingsEditor with context %}
        {{ SettingsEditor() }}
        """,
        files_html=files_html,
        version=version,
        revision_number=revision_number,
        user_dicts=user_dicts,
        settings_dict=settings_dict,
        settings_doc_dict=settings_doc_dict,
        user_settings_doc_dict=user_settings_doc_dict,
        access_group=access_group,
        access_groups=access_groups,
        users=users,
    )
    backup_working_config()
    return settings_editor_html


@main.route("/app_view?<app_id>", methods=["GET"])
def app_view(app_id):
    access_group, redirect_url = get_access_group(current_user)
    apps, tags = get_apps_and_tags(access_group)
    if redirect_url:
        return redirect(redirect_url)
    app_db = Apps.query.filter_by(id=app_id).first()
    return render_template(
        "main/app-view.html",
        url=f"{app_db.prefix}{app_db.url}",
        title=app_db.name,
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@main.route("/load_data_source", methods=["GET"])
def load_data_source():
    data_source = DataSources.query.filter_by(id=request.args.get("id")).first()
    data = get_data_source(data_source)
    return data


@main.route("/update_message_read", methods=["GET"])
def update_message_read():
    mark_update_message_read()
    return "ok"


@main.route("/build_action_provider_url", methods=["GET"])
def build_action_provider_url():
    url = render_template_string(
        request.args.get("action"), value=request.args.get("value")
    )
    return url


@main.route("/get_card_editor_form", methods=["GET"])
def get_card_editor_form():
    app_templates = None
    if request.args.get("type", None) == "app":
        new_app = Apps(type="app")
        card = row2dict(new_app)
        app_templates = get_template_apps()

    elif request.args.get("type", None) == "collection":
        new_app = Apps(type="collection")
        card = row2dict(new_app)
        card["urls"] = '{"url": "", "icon": "", "name": "", "open_in": ""}'
    elif request.args.get("type", None) == "custom":
        new_app = Apps(type="custom")
        card = row2dict(new_app)
    else:
        card_db = Apps.query.filter_by(id=request.args.get("app_id")).first()
        card = row2dict(card_db)
        card["tags"] = ",".join([tag.name for tag in card_db.tags])
        card["groups"] = ",".join([group.name for group in card_db.access_groups])
        card["data_sources"] = ",".join([ds.name for ds in card_db.data_sources])

    if not card.get("tags", None):
        card["tags"] = ""
    if not card.get("groups", None):
        card["groups"] = ""
    if not card.get("data_sources", None):
        card["data_sources"] = ""

    if card["urls"] != "None":
        urls = card["urls"]
        del card["urls"]
        card["urls"] = ["list"] + [
            json.loads(url_json)
            for url_json in urls.replace("},{", "}%,%{").split("%,%")
        ]
    doc_dict = get_card_doc_dict(card["type"])
    if card["type"] == "app":
        anchor = "cards-apps"
    elif card["type"] == "collection":
        anchor = "cards-collection"
    elif card["type"] == "custom":
        anchor = "cards-custom"
    doc_dict["docs_url"] = url_for("docs_system.docs_cards", _anchor=anchor)
    form_html = render_template_string(
        """
        {% from 'main/ini-form.html' import INIForm %}
        {% if card['name'] != 'None' %}
            <h5 class="theme-primary-text">Editing {{ card['name'] }}</h5>
        {% else %}
            <h5 class="theme-primary-text">New {{ doc_dict['name'] }}</h5>
        {% endif %}
        {{ INIForm(card, doc_dict, location="card-editor", app_templates=app_templates) }}
        """,
        card=card,
        doc_dict=doc_dict,
        app_templates=app_templates,
    )
    return form_html


@main.route("/get_card_editor_ds_form", methods=["GET"])
def get_card_editor_ds_form():
    ds_selector = None

    if request.args.get("new", None) == "True":
        data_source = {}
        doc_dict = {}
        ds_selector = [ds["name"] for ds in data_sources_doc_dicts(get_all=True)]
    elif request.args.get("platform", None):
        doc_dict = data_sources_doc_dicts(platform_name=request.args.get("platform"))[0]
        for variable in doc_dict["variables"]:

dashmachine/templates/global_macros.html
<!--GLOBAL SWITCH-->
{% macro switch(
id="",
form_obj=None,
label_left="",
label_right="",
value=None,
size="",
name="",
onclickval=None,
data={}) %}
    <div class="switch col {{ size }}"
            {% for key, value in data.items() %}
         data-{{key}}="{{value}}"
            {% endfor %}
    >
        {{ label_left }}
        <label>
            {% if form_obj%}

                {% if value == True %}
                    {{ form_obj(type="checkbox", checked="checked", onclick=onclickval, id=id, name=name) }}
                {% else %}
                    {{ form_obj(type="checkbox", onclick=onclickval, id=id, name=name) }}
                {% endif %}

            {% else %}

                {% if value == 'True' %}
                    <input id="{{id}}" name="{{name}}" type="checkbox" checked>
                {% else %}
                    <input id="{{id}}" name="{{name}}" type="checkbox">
                {% endif %}

            {% endif %}
            <span class="lever"></span>
        </label>
        {{ label_right }}
    </div>
{% endmacro %}


<!--GLOBAL BUTTON-->
{% macro button(
text,
id=None,
class=None,
data={},
icon=None,
float="right",
href=None,
target_blank=None
)%}
    <a class="waves-effect waves-light btn {{class}} {{float}} theme-on-primary-text"
            {% if id %}
       id="{{id}}"
            {% endif %}

            {% if href %}
       href="{{href}}"
            {% endif %}

            {% if target_blank %}
       target="_blank"
            {% endif %}

            {% for key, value in data.items() %}
       data-{{key}}="{{value}}"
            {% endfor %}

       style="background-color: var(--theme-primary);
          border-radius: 8px;
          margin-right: 5px;
          margin-left: 5px;">
        {% if icon %}
            <i class="material-icons-outlined left">{{icon}}</i>
        {% endif %}
        {{text}}</a>
{% endmacro %}

<!--GLOBAL TEXT INPUT FIELD (INCLUDES PARENT COL)-->
{% macro input(
id=None,
label=None,
name="",
form_obj=None,
val="",
size="s6",
class="",
col_class="",
col_id="",
icon=None,
spacer_icon=False,
required='',
helper=None,
col_style=None
)%}
    <div id="{{col_id}}" class="input-field col {{ size }} {{ col_class }}" style="{{ col_style }}">
        {% if spacer_icon == True %}
            <i class="material-icons-outlined prefix hide"> home </i>
        {% endif %}
        {% if icon %}
            <i class="material-icons-outlined prefix"> {{icon}} </i>
        {% endif %}

        {% if form_obj %}
            {% if required == "required" %}
                {{ form_obj(id=id, value=val, class="validate " + class, required=required) }}
            {% else %}
                {{ form_obj(id=id, value=val, class="validate " + class) }}
            {% endif %}
        {% else %}
            <input {% if id %}id="{{ id }}"{% endif %} {% if id %}name="{{ name }}"{% endif %} type="text" {% if val and val|length > 0 %}value="{{val}}"{% endif %} class="validate {{class}}" {{required}}>
        {% endif %}

        {% if label %}
            <label for="{{ id }}">{{ label }}</label>
        {% endif %}

        {% if helper %}
            <span class="helper-text">{{helper}}</span>
        {% endif %}

    </div>
{% endmacro %}

{% macro preload_circle() %}
    <div class="preloader-wrapper active center">
        <div class="spinner-layer spinner-blue">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
        </div>

        <div class="spinner-layer spinner-red">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
        </div>

        <div class="spinner-layer spinner-yellow">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
        </div>

        <div class="spinner-layer spinner-green">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
        </div>
    </div>
{% endmacro %}

{% macro select(
id='',
form_obj=None,
size="s12",
label=None,
class=''
) %}
    <div class="input-field col {{size}}">
        {{ form_obj(id=id, class=class, placeholder="Tags") }}
        {% if label %}
            <label>{{ label }}</label>
        {% endif %}
    </div>
{% endmacro %}

{% macro DMLogo(size="64px", style="", class="") %}
    <svg style="isolation:isolate; height: {{size}}; width: {{size}}; {{ style }}" viewBox="0 0 88 88" xmlns="http://www.w3.org/2000/svg" class="{{ class }} dm-logo-svg">
        <defs>
            <clipPath id="dm-logo-clip-path">
                <rect width="88" height="88"/>
            </clipPath>
        </defs>
        <g clip-path="url(#dm-logo-clip-path)">
            <rect width="88" height="88" fill-opacity="0"/>
            <path d="m23.544 69.951c2.2 1.773 4.849 3.098 7.929 4.4l1.32 11.449c0 1.32 0.88 2.2 2.2 2.2h17.6c1.32 0 2.2-0.88 2.2-2.2l1.324-11.449c2.627-0.875 5.725-2.627 7.925-4.4l10.551 4.849c0.875 0.449 2.2 0 2.649-1.32l8.8-15.4c0.871-1.329 0.431-2.631-0.449-3.08l-9.249-6.6c0.449-1.32 0.449-3.08 0.449-4.4s-0.449-3.08-0.449-4.4l9.249-7.049c1.324-0.431 1.324-1.751 0.449-3.071l-8.8-15.4c-0.449-0.88-1.769-1.329-2.649-0.88l-10.551 4.4c-2.2-1.751-4.849-3.08-7.929-4.4l-1.32-11c0-1.32-0.88-2.2-2.2-2.2h-17.6c-1.32 0-2.2 0.88-2.2 2.2l-1.325 11.449c-2.626 0.875-5.724 2.627-7.924 4.4l10.751 11.164c2.74-1.781 6.004-2.813 9.498-2.813 9.68 0 17.6 7.92 17.6 17.6s-7.92 17.6-17.6 17.6c-3.726 0-7.19-1.173-10.036-3.177l-10.213 11.528z" fill="#ff9800"/>
            <path class="clear-fill" d="m11.381 48.4c0-1.32-0.449-3.08-0.449-4.4s0-3.08 0.449-4.4l-9.249-6.6c-0.88-0.449-1.32-1.751-0.449-3.08l8.8-15.4c0.449-1.32 1.773-1.764 2.649-1.32l10.551 4.849c2.2-1.773 5.298-3.525 7.924-4.4l1.325-11.449c0-1.32 0.88-2.2 2.2-2.2h17.6c1.32 0 2.2 0.88 2.2 2.2l1.32 11c3.08 1.32 5.729 2.649 7.929 4.4l10.551-4.4c0.88-0.449 2.2 0 2.649 0.88l8.8 15.4c0.875 1.32 0.875 2.64-0.449 3.071l-9.249 7.049c0 1.32 0.449 3.08 0.449 4.4s0 3.08-0.449 4.4l9.249 6.6c0.88 0.449 1.32 1.751 0.449 3.08l-8.8 15.4c-0.449 1.32-1.774 1.769-2.649 1.32l-10.551-4.849c-2.2 1.773-5.298 3.525-7.925 4.4l-1.324 11.449c0 1.32-0.88 2.2-2.2 2.2h-17.6c-1.32 0-2.2-0.88-2.2-2.2l-1.32-11.449c-3.08-1.302-5.729-2.627-7.929-4.4l-10.551 4.849c-0.88 0.449-2.2 0-2.649-0.88l-8.8-15.4c-0.427-0.871-0.427-2.2 0.449-3.071l9.249-7.049zm32.551 13.2c9.68 0 17.6-7.92 17.6-17.6s-7.92-17.6-17.6-17.6-17.6 7.92-17.6 17.6 7.92 17.6 17.6 17.6z" fill="none"/>
            <path d="m44 32.214h-16.937c-1.06 0-1.92 0.861-1.92 1.92v19.732c0 1.059 0.86 1.92 1.92 1.92h16.937c6.505 0 11.786-5.281 11.786-11.786s-5.281-11.786-11.786-11.786z" fill="#ff9800" fill-rule="evenodd"/>
        </g>
    </svg>

{% endmacro %}

{% macro SidenavToggle() %}
    <div id="sidenav-toggle-svg-container" class="hide">
        <svg id="sidenav-expand-area-svg" width="10pt" height="81pt" style="isolation:isolate" viewBox="0 0 10 81" xmlns="http://www.w3.org/2000/svg">
            <defs>
                <clipPath id="sidenav-expand-area-svg-cp">
                    <rect width="10" height="81"/>
                </clipPath>
            </defs>
            <g clip-path="url(#sidenav-expand-area-svg-cp)">
                <rect width="10" height="81" fill-opacity="0"/>
                <path class="primary" d="m0 0h7.57c1.341 0 2.43 1.089 2.43 2.43v76.14c0 1.341-1.089 2.43-2.43 2.43h-7.57v-81z"/>
                <path class="on-primary" d="m3.167 43.177c-0.062 0-0.121-0.014-0.173-0.043-0.131-0.071-0.208-0.223-0.208-0.413v-4.443c0-0.193 0.075-0.343 0.208-0.413 0.132-0.07 0.3-0.052 0.46 0.055l3.303 2.174c0.155 0.102 0.243 0.251 0.243 0.408 0 0.158-0.088 0.306-0.243 0.408l-3.303 2.174c-0.095 0.059-0.194 0.093-0.287 0.093z" fill="#fff"/>
            </g>
        </svg>

        <br>

        <svg id="sidenav-drag-handle-svg" width="10pt" height="19pt" style="isolation:isolate;" viewBox="0 0 10 19" xmlns="http://www.w3.org/2000/svg">
            <defs>
                <clipPath id="sidenav-drag-handle-svg-cp">
                    <rect width="10" height="19"/>
                </clipPath>
            </defs>
            <g clip-path="url(#sidenav-drag-handle-svg-cp)">
                <rect width="10" height="19" fill-opacity="0"/>
                <path class="primary" d="m0 0h8.05c1.076 0 1.95 0.874 1.95 1.95v15.1c0 1.076-0.874 1.95-1.95 1.95h-8.05v-19z"/>
                <path class="on-primary" d="m5 5.929c0.563 0 1.02 0.457 1.02 1.02s-0.457 1.02-1.02 1.02-1.02-0.457-1.02-1.02 0.457-1.02 1.02-1.02zm0 2.551c0.563 0 1.02 0.457 1.02 1.02s-0.457 1.02-1.02 1.02-1.02-0.457-1.02-1.02 0.457-1.02 1.02-1.02zm0 2.551c0.563 0 1.02 0.457 1.02 1.02s-0.457 1.02-1.02 1.02-1.02-0.457-1.02-1.02 0.457-1.02 1.02-1.02z" fill="#fff" fill-rule="evenodd"/>
            </g>
        </svg>
    </div>
{% endmacro %}

{% macro ActionBar(tags, location) %}
    <div class="row card-filter-container" style="z-index: 6000">
        <div class="col s12 m12 {% if location == "home" %} l6 xl4{% endif %} input-field">
            <span>
                <i class="material-icons prefix card-search-icon">search</i>
                <input data-search-providers-url="{{ url_for('main.build_action_provider_url') }}"
                       type="text"
                       class="card-filter action-bar theme-surface-transparent"
                       placeholder="Search.." autofocus>

                {% if tags|length > 1 %}
                    <i class="toggle-tag-expand-all-btn material-icons right filter-action pointer">unfold_less</i>
                    <!-- Dropdown Trigger -->
                    <a class='dropdown-trigger filter-tags-dropdown-trigger' data-target='filter-tags-dropdown-{{ location }}'>
                        <i class="material-icons right filter-action pointer">tune</i>
                    </a>

                    <!-- Dropdown Structure -->
                    <ul id='filter-tags-dropdown-{{ location }}' class='filter-tags-dropdown dropdown-content' style="min-width: 50%; z-index: 7000">
                        <li><a class="filter-tags-dropdown-a show-all">
                            <i class="material-icons theme-secondary-text">close</i> Show all
                        </a></li>
                        {% for tag in tags %}
                            <li><a class="filter-tags-dropdown-a pointer">
                                <div class="row">
                                    <div class="col s2" style="position: relative; top: 4px;">
                                        <label>
                                            <input type="checkbox" data-name="{{ tag.name }}"/>
                                            <span></span>
                                        </label>
                                    </div>
                                    <div class="col s10" style="position: relative; top: 6px;">
                                        {{ tag.name }}
                                    </div>
                                </div>
                            </a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </span>
        </div>
    </div>
{% endmacro %}

dashmachine/templates/page_template.html
{% extends "main/top-and-side-nav.html" %}
{% block page_vendor_css %}
{% endblock page_vendor_css %}

{% block page_lvl_css %}
{% endblock page_lvl_css %}

{% block body_class %}
{% endblock body_class %}

{% block content %}
{% endblock content %}

{% block page_vendor_js %}
{% endblock page_vendor_js %}

{% block page_lvl_js %}
{% endblock page_lvl_js %}