dashmachine/settings_system/models.py
from dashmachine import db


class Settings(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    theme = db.Column(db.String())
    accent = db.Column(db.String())
    layout = db.Column(db.String())
    background = db.Column(db.String())
    roles = db.Column(db.String())
    home_access_groups = db.Column(db.String())
    settings_access_groups = db.Column(db.String())
    custom_app_title = db.Column(db.String())
    sidebar_default = db.Column(db.String())
    tags_expanded = db.Column(db.String())

dashmachine/settings_system/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField


class ConfigForm(FlaskForm):
    config = TextAreaField()
    wiki_name = StringField()
    wiki_permalink_new = StringField()
    wiki_author = StringField()
    wiki_description = TextAreaField()
    wiki_tags = StringField()

dashmachine/settings_system/routes.py
import os
from shutil import move
from configparser import ConfigParser
from flask_login import current_user
from flask import render_template, request, Blueprint, jsonify, redirect, url_for
from dashmachine.user_system.forms import UserForm
from dashmachine.user_system.models import User
from dashmachine.main.utils import public_route, check_groups
from dashmachine.main.read_config import read_config
from dashmachine.main.models import Files
from dashmachine.settings_system.forms import ConfigForm
from dashmachine.settings_system.utils import load_files_html, get_config_html
from dashmachine.settings_system.models import Settings
from dashmachine.paths import (
    backgrounds_images_folder,
    icons_images_folder,
    user_data_folder,
    template_apps_folder,
)
from dashmachine.version import version, revision_number

settings_system = Blueprint("settings_system", __name__)


@public_route
@settings_system.route("/settings", methods=["GET"])
def settings():
    settings_db = Settings.query.first()
    if not check_groups(settings_db.settings_access_groups, current_user):
        return redirect(url_for("main.home"))

    config_form = ConfigForm()
    user_form = UserForm()
    user_form.role.choices += [(role, role) for role in settings_db.roles.split(",")]
    with open(os.path.join(user_data_folder, "config.ini"), "r") as config_file:
        config_form.config.data = config_file.read()
    files_html = load_files_html()

    template_apps = []
    config = ConfigParser()
    for template_app_ini in os.listdir(template_apps_folder):
        config.read(os.path.join(template_apps_folder, template_app_ini))
        entry = config[template_app_ini.replace(".ini", "")]
        template_apps.append(f"{template_app_ini.replace('.ini', '')}&&{entry['icon']}")

    users = User.query.all()
    config_readme = get_config_html()
    return render_template(
        "settings_system/settings.html",
        config_form=config_form,
        files_html=files_html,
        user_form=user_form,
        template_apps=",".join(template_apps),
        version=version,
        revision_number=revision_number,
        users=users,
        config_readme=config_readme,
    )


@settings_system.route("/settings/save_config", methods=["POST"])
def save_config():
    with open(os.path.join(user_data_folder, "config.ini"), "w") as config_file:
        config_file.write(request.form.get("config"))
    msg = read_config()
    return jsonify(data=msg)


@settings_system.route("/settings/add_images", methods=["POST"])
def add_images():
    if request.form.get("folder") == "icons":
        dest_folder = icons_images_folder
    elif request.form.get("folder") == "backgrounds":
        dest_folder = backgrounds_images_folder
    for cached_file in request.form.get("files").split(","):
        file = Files.query.filter_by(cache=cached_file).first()
        new_path = os.path.join(dest_folder, file.name)
        move(file.path, new_path)
    return load_files_html()


@settings_system.route("/settings/delete_file", methods=["GET"])
def delete_file():
    if request.args.get("folder") == "backgrounds":
        file = os.path.join(backgrounds_images_folder, request.args.get("file"))
    if request.args.get("folder") == "icons":
        file = os.path.join(icons_images_folder, request.args.get("file"))
    os.remove(file)
    return load_files_html()


@settings_system.route("/settings/get_app_template", methods=["GET"])
def get_app_template():
    fn = os.path.join(template_apps_folder, f"{request.args.get('name')}.ini")
    with open(fn, "r") as template_app_ini:
        template = template_app_ini.read().replace("\n", "<br>")
    return template

dashmachine/templates/settings_system/files.html
{% from 'global_macros.html' import button %}
{% from 'main/tcdrop.html' import tcdrop %}

{% macro FilesTab() %}
    <div class="row">
        <h5>Images</h5>
        <form id="add-images-form">
            <div class="input-field col s12 mt-4">
                <select name="folder">
                    <option value="icons">Icons</option>
                    <option value="backgrounds">Backgrounds</option>
                </select>
                <label>Folder</label>
            </div>
            <input name="files" id="add-images-input" class="hide">
        </form>
        <div class="col s12">
            {{ tcdrop(allowed_types='apng,bmp,gif,ico,cur,jpg,jpeg,jfif,pjpeg,pjp,png,svg,tif,tiff,webp', id="images-tcdrop", max_files="30") }}
            {{ button(text="save", icon="save", id="save-images-btn", float="left", data={"url": url_for('settings_system.add_images')}) }}
        </div>
    </div>

    <div class="row">
        <div id="files-div">{{ files_html|safe }}</div>
    </div>
{% endmacro %}

{% macro Files(icons, backgrounds) %}
    <style>
        .file-title {
            position: relative;
            top: .6em;
        }
    </style>

    <div class="divider"></div>
    <div class="row">
        <div class="col s12">
            <ul class="collection with-header">
                <li class="collection-header theme-primary theme-on-primary-text">Backgrounds</li>
                {% if backgrounds %}
                    {% for background in backgrounds %}
                        <li class="theme-surface collection-item pt-2 pb-2 avatar">
                            <div class="row">
                                <div class="col s12 mt-2">
                                    <a href="static/images/backgrounds/{{ background }}" target="_blank">
                                        <img src="static/images/backgrounds/{{ background }}" alt="" class="circle">
                                    </a>
                                    <span class="selectable-all copy-target file-title"  style="word-wrap: break-word;">static/images/backgrounds/{{ background }}</span>
                                </div>

                                <div class="col s12 mt-2">
                                    <span class="theme-secondary-text right">
                                        <i class="material-icons-outlined icon-btn copy-btn">filter_none</i>
                                        <i class="material-icons-outlined icon-btn delete-file-btn"
                                           data-url="{{ url_for('settings_system.delete_file') }}"
                                           data-folder="backgrounds"
                                           data-file="{{ background }}">close
                                        </i>
                                    </span>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                    <li class="collection-item">No files yet</li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="divider"></div>
    <div class="row">
        <div class="col s12">
            <div class="collection with-header">
                <div class="collection-header theme-primary theme-on-primary-text">Icons</div>
                {% if icons %}
                    {% for icon in icons %}
                        <div class="theme-surface collection-item pt-2 pb-2 avatar">
                            <div class="row">
                                <div class="col s12 mt-2">
                                    <a href="static/images/icons/{{ icon }}" target="_blank">
                                        <img src="static/images/icons/{{ icon }}" alt="" class="circle">
                                    </a>
                                    <span class="selectable-all copy-target file-title" style="word-wrap: break-word;">static/images/icons/{{ icon }}</span>
                                </div>

                                <div class="col s12 mt-2">
                                    <span class="theme-secondary-text right">
                                        <i class="material-icons-outlined icon-btn copy-btn">filter_none</i>
                                        <i class="material-icons-outlined icon-btn delete-file-btn"
                                           data-url="{{ url_for('settings_system.delete_file') }}"
                                           data-folder="icons"
                                           data-file="{{ icon }}">close
                                        </i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <li class="collection-item">No files yet</li>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
        $( document ).ready(function() {
            init_copy_btn(".collection-item");
            $(".delete-file-btn").on('click', function(e) {
                $.ajax({
                    url: $(this).attr('data-url'),
                    type: 'GET',
                    data: {folder: $(this).attr("data-folder"), file: $(this).attr("data-file")},
                    success: function(data){
                        $("#files-div").empty();
                        $("#files-div").append(data);
                    }
                });
            });
        });
    </script>
{% endmacro %}

{{ Files(icons, backgrounds) }}

dashmachine/templates/settings_system/settings.html
{% extends "main/layout.html" %}
{% from 'global_macros.html' import input, button, select %}
{% from 'main/tcdrop.html' import tcdrop %}
{% from 'settings_system/files.html' import FilesTab with context %}
{% block page_vendor_css %}
{% endblock page_vendor_css %}

{% block page_lvl_css %}
    {{ process_css_sources(src="settings_system/settings.css")|safe }}
    {% if settings.background and settings.background != 'None' %}
        <style>
            #main {
                background-image: url("{{ settings.background }}");
                background-size: cover;
                background-attachment: fixed;
                min-height: 100vh;
            }
        </style>
    {% endif %}
{% endblock page_lvl_css %}

{% block content %}

    <div id="main" class="main-full">
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l6">
                    <div class="card">
                        <div class="card-content">
                            <div class="row">
                                <div class="col s12">
                                    <span>
                                        <span style="font-size: 2rem; position: relative; top: 8px;">Config.ini</span>
                                        {{ button(
                                        icon="save",
                                        id="save-config-btn",
                                        float="right",
                                        class="ml-0 mt-1 mb-1",
                                        data={'url': url_for('settings_system.save_config')},
                                        text="save"
                                        ) }}
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="card-action scrollbar settings-page-card-left">
                            <form id="config-form">
                                {{ input(
                                size="s12",
                                class="materialize-textarea code",
                                form_obj=config_form.config,
                                id="config-textarea"
                                ) }}
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col s12 m12 l6">
                    <div class="card">
                        <div class="card-content pr-2">

                            <div class="row">
                                <div class="col s12 mb-2">
                                    <ul class="tabs tabs-fixed-width">
                                        <li class="tab col s3"><a href="#settings-readme">
                                            <i class="material-icons-outlined">settings</i>
                                        </a></li>

                                        <li class="tab col s3"><a href="#cards-readme">
                                            <i class="material-icons-outlined">aspect_ratio</i>
                                        </a></li>

                                        <li class="tab col s3"><a href="#data-sources-readme">
                                            <i class="material-icons-outlined">language</i>
                                        </a></li>

                                        <li class="tab col s3"><a href="#images">
                                            <i class="material-icons-outlined">photo_library</i>
                                        </a></li>

                                        <li class="tab col s3"><a href="#about">
                                            <i class="material-icons-outlined">security</i>
                                        </a></li>
                                    </ul>
                                </div>

                                <div id="images" class="col s12 scrollbar settings-page-card-right">
                                    {{ FilesTab() }}
                                </div>

                                <div id="settings-readme" class="col s12 scrollbar settings-page-card-right scrollbar-x">
                                    {{ config_readme['settings']|safe }}
                                </div>

                                <div id="cards-readme" class="col s12 scrollbar settings-page-card-right scrollbar-x">
                                    <h4>Cards</h4>
                                    <h5>Card Templates</h5>
                                    <span>Search for preconfigured cards included with DashMachine.</span>
                                    <div class="row card-filter-container" style="position: relative;">
                                        <div class="col s12 input-field">
                                            <span>
                                                <i class="material-icons prefix card-search-icon">search</i>
                                                <input type="text" id="templates-filter"
                                                       class="card-filter theme-surface-1 autocomplete"
                                                       data-url="{{ url_for('settings_system.get_app_template') }}"
                                                       data-template_apps="{{ template_apps }}"
                                                       placeholder="Search for app (e.g. Nextcloud)">
                                            </span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12 scrollbar">
                                            <div id="template-div" class="selectable code"></div>
                                        </div>
                                    </div>

                                    {{ config_readme['cards']|safe }}
                                </div>

                                <div id="data-sources-readme" class="col s12 scrollbar settings-page-card-right scrollbar-x">
                                    {{ config_readme['data_sources']|safe }}
                                </div>

                                <div id="about" class="col s12 scrollbar settings-page-card-right">
                                    <div class="row">
                                        <div class="card theme-surface-1">
                                            <div class="card-content center-align">
                                                <img src="static/images/logo/full.svg">
                                                <h5>DashMachine</h5>
                                                <div class="divider"></div>
                                                <p class="font-weight-900 mb-2">Version:</p>
                                                <p class="mb-2">{{ version }}-{{ revision_number }}</p>

                                                <div class="divider"></div>
                                                <p class="font-weight-900 mb-2">Author:</p>
                                                <p class="mb-2">Ross Mountjoy (<a href="https://github.com/rmountjoy92" target="_blank"> Github </a>)</p>

                                                <div class="divider"></div>
                                                <p class="font-weight-900 mb-2">Source code:</p>
                                                <p class="mb-2"><a href="https://github.com/rmountjoy92/DashMachine" target="_blank"> Repo</a></p>

                                                <div class="divider"></div>
                                                <p class="font-weight-900 mb-2">Reddit:</p>
                                                <p class="mb-2"><a href="https://www.reddit.com/r/DashMachine/" target="_blank"> r/DashMachine</a>

                                                <div class="divider"></div>
                                                <p class="font-weight-900 mb-2">Donations:</p>
                                                <p class="mb-2"><a href="https://liberapay.com/rmountjoy/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a></p>
                                                <p class="mb-2"><a href="https://www.bountysource.com/teams/dashmachine-app" target="_blank"> Bountysource donation link</a></p>

                                                <div class="divider"></div>
                                                <p class="font-weight-900 mb-2">Bounties for new features:</p>
                                                <p class="mb-2"><a href="https://www.bountysource.com/" target="_blank"> Bountysource link</a></p>
                                                <p class="mb-2"><a href="https://github.com/bountysource/core/wiki/Frequently-Asked-Questions" target="_blank"> Bountysource faqs</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock content %}

{% block page_vendor_js %}
{% endblock page_vendor_js %}

{% block page_lvl_js %}
{{ process_js_sources(src="settings_system/settings.js")|safe }}
{% endblock page_lvl_js %}