dashmachine/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField


class TagsForm(FlaskForm):
    tags = SelectField(choices=[("All tags", "All tags")])

dashmachine/docs_system/routes.py
import os
from flask import render_template, Blueprint, redirect, request
from flask_login import current_user
from dashmachine.paths import root_folder, wiki_folder
from dashmachine.docs_system.core_docs import (
    settings_doc_dict,
    user_settings_doc_dict,
    apps_doc_dict,
    collections_doc_dict,
    custom_card_doc_dict,
    data_sources_doc_dicts,
    access_groups_doc_dict,
)
from dashmachine.docs_system.utils import (
    get_md_from_file,
    get_md_from_dict,
    get_toc_md_from_dicts,
    create_edit_wiki,
)
from dashmachine.moment import create_moment
from dashmachine.main.utils import get_apps_and_tags, get_access_group
from dashmachine.main.models import Wiki, WikiTags

docs_system = Blueprint("docs_system", __name__)


@docs_system.route("/docs_home", methods=["GET"])
def docs_home():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    apps, tags = get_apps_and_tags(access_group)
    if redirect_url:
        return redirect(redirect_url)
    return render_template(
        "docs_system/docs-home.html",
        about_html=get_md_from_file(os.path.join(root_folder, "README.md")),
        install_html=get_md_from_file("install.md"),
        getting_started_html=get_md_from_file("getting-started.md"),
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/docs_main_settings", methods=["GET"])
def docs_main_settings():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    return render_template(
        "docs_system/docs-main-settings.html",
        main_settings_html=get_md_from_dict(settings_doc_dict),
        user_settings_html=get_md_from_dict(user_settings_doc_dict),
        ag_settings_html=get_md_from_dict(access_groups_doc_dict),
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/docs_cards", methods=["GET"])
def docs_cards():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    return render_template(
        "docs_system/docs-cards.html",
        apps_html=get_md_from_dict(apps_doc_dict),
        collections_html=get_md_from_dict(collections_doc_dict),
        custom_cards_html=get_md_from_dict(custom_card_doc_dict),
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/docs_data_sources", methods=["GET"])
def docs_data_sources():
    access_group, redirect_url = get_access_group(current_user, page="docs")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    doc_dicts = data_sources_doc_dicts(get_all=True)
    data_sources_html = get_toc_md_from_dicts(doc_dicts)
    for doc in doc_dicts:
        data_sources_html += f"\n\n{get_md_from_dict(doc)}"
    return render_template(
        "docs_system/docs-data-sources.html",
        data_sources_main_html=get_md_from_file("data-sources.md"),
        creating_platforms_html=get_md_from_file("creating-platforms.md"),
        platform_methods_html=get_md_from_file("platform-methods.md"),
        data_sources_html=data_sources_html,
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/wiki_tags", methods=["GET"])
def wiki_tags():
    access_group, redirect_url = get_access_group(current_user, page="wikis")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)

    wiki_tags_db = WikiTags.query.all()
    return render_template(
        "docs_system/wiki-tags.html",
        access_group=access_group,
        apps=apps,
        tags=tags,
        wiki_tags=wiki_tags_db,
    )


@docs_system.route("/wikis", methods=["GET"])
def wikis():
    access_group, redirect_url = get_access_group(current_user, page="wikis")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)

    if request.args.get("tag", None):
        tag = WikiTags.query.filter_by(id=request.args.get("tag")).first()
        wikis_db = tag.wikis
    else:
        tag = None
        wikis_db = Wiki.query.all()
    for wiki_db in wikis_db:
        wiki_db.updated_moment = create_moment(wiki_db.updated)
    return render_template(
        "docs_system/wikis.html",
        access_group=access_group,
        apps=apps,
        tags=tags,
        wikis=wikis_db,
        tag=tag,
    )


@docs_system.route("/wiki-<permalink>", methods=["GET"])
def wiki(permalink=None):
    access_group, redirect_url = get_access_group(current_user, page="wiki")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)

    wiki_db = Wiki.query.filter_by(permalink=permalink).first()
    if wiki_db:
        wiki_fp = os.path.join(wiki_folder, f"{wiki_db.name}.md")
        with open(wiki_fp, "r") as file:
            wiki_md = file.read()
        wiki_md_html = get_md_from_file(file=wiki_db.name, full_path=wiki_fp)
    else:
        wiki_md_html = None

    if wiki_db.wiki_tags.count() > 0:
        wiki_db.tags_str = ",".join([tag.name for tag in wiki_db.wiki_tags])
    return render_template(
        "docs_system/wiki.html",
        access_group=access_group,
        wiki=wiki_db,
        wiki_md_html=wiki_md_html,
        wiki_md=wiki_md,
        apps=apps,
        tags=tags,
    )


@docs_system.route("/save_wiki", methods=["POST"])
def save_wiki():
    create_edit_wiki(
        permalink=request.form.get("wiki_permalink", None),
        permalink_new=request.form.get("wiki_permalink_new", None),
        name=request.form.get("wiki_name", None),
        author=request.form.get("wiki_author", None),
        description=request.form.get("wiki_description", None),
        md=request.form.get("config", None),
        tags=request.form.get("wiki_tags", None),
    )
    return "ok"

dashmachine/main/__init__.py
#!/usr/bin/env python3

dashmachine/main/routes.py
import os
import glob
import json
from secrets import token_hex
from htmlmin.main import minify
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint,
    jsonify,
    render_template_string,
)
from flask_login import current_user
from dashmachine.main.models import Files, Apps, DataSources
from dashmachine.main.utils import (
    get_data_source,
    mark_update_message_read,
    row2dict,
    get_apps_and_tags,
    get_access_group,
    backup_working_config,
    get_template_apps,
)
from dashmachine.main.modify_config import modify_config
from dashmachine.settings_system.models import Settings
from dashmachine.settings_system.forms import ConfigForm
from dashmachine.settings_system.utils import load_files_html
from dashmachine.docs_system.utils import get_card_doc_dict
from dashmachine.docs_system.core_docs import (
    configured_data_sources_doc_dicts,
    settings_doc_dict,
    user_settings_doc_dict,
    access_groups_doc_dict,
    data_sources_doc_dicts,
)
from dashmachine.user_system.models import User, AccessGroups
from dashmachine.paths import cache_folder, user_data_folder
from dashmachine.version import version, revision_number
from dashmachine import app, db


main = Blueprint("main", __name__)


# ------------------------------------------------------------------------------
# intial routes and functions (before/after request)
# ------------------------------------------------------------------------------
@app.after_request
def response_minify(response):
    """
    minify html response to decrease site traffic
    """
    if response.content_type == "text/html; charset=utf-8":
        response.set_data(minify(response.get_data(as_text=True)))

        return response
    return response


# ------------------------------------------------------------------------------
# /home
# ------------------------------------------------------------------------------
@main.route("/")
@main.route("/home", methods=["GET"])
def home():
    access_group, redirect_url = get_access_group(current_user, page="home")
    if redirect_url:
        return redirect(redirect_url)
    apps, tags = get_apps_and_tags(access_group)
    return render_template(
        "main/home.html", apps=apps, tags=tags, access_group=access_group, page="home"
    )


# ------------------------------------------------------------------------------
# /home modules
# ------------------------------------------------------------------------------
@main.route("/load_apps", methods=["GET"])
def load_apps():
    access_group, redirect_url = get_access_group(current_user)
    apps, tags = get_apps_and_tags(access_group)

    if request.args.get("home", None) == "true":
        html = render_template_string(
            """
            {% from 'main/cards.html' import HomeCards %}
            {{ HomeCards(apps, tags) }}
            """,
            apps=apps,
            tags=tags,
        )
    elif request.args.get("sidenav", None) == "true":
        html = render_template_string(
            """
            {% from 'main/cards.html' import SidenavApps %}
            {{ SidenavApps(apps, tags) }}
            """,
            apps=apps,
            tags=tags,
        )
    return html


@main.route("/load_card_editor", methods=["GET"])
def load_card_editor():
    access_group, redirect_url = get_access_group(current_user)
    apps, tags = get_apps_and_tags(access_group)
    data_sources = []
    for ds in DataSources.query.all():
        data_sources.append({"id": ds.id, "name": ds.name, "platform": ds.platform})
    card_editor_html = render_template_string(
        """
        {% from 'main/card-editor.html' import CardEditor with context %}
        {{ CardEditor() }}
        """,
        data_sources=data_sources,
        apps=apps,
    )
    return card_editor_html


@main.route("/load_config_editor", methods=["GET"])
def load_config_editor():
    config_form = ConfigForm()
    with open(os.path.join(user_data_folder, "config.ini"), "r") as config_file:
        config_form.config.data = config_file.read()
    config_editor_html = render_template_string(
        """
        {% from 'main/config-editor.html' import ConfigEditor with context %}
        {{ ConfigEditor() }}
        """,
        config_form=config_form,
    )
    return config_editor_html


@main.route("/load_settings_editor", methods=["GET"])
def load_settings_editor():
    settings_db = Settings.query.first()
    files_html = load_files_html()
    access_group, redirect_url = get_access_group(current_user)

    access_groups = AccessGroups.query.all()
    users = User.query.all()

    # GUI DICTS
    user_dicts = [row2dict(user) for user in User.query.all()]
    for user_dict in user_dicts:
        user_dict["password"] = None
    user_settings_doc_dict["docs_url"] = url_for(
        "docs_system.docs_main_settings", _anchor="user-settings"
    )
    settings_dict = row2dict(settings_db)
    settings_doc_dict["docs_url"] = url_for("docs_system.docs_main_settings")
    settings_dict["action_providers"] = ["list"] + [
        json.loads(tag_json)
        for tag_json in settings_dict["action_providers"]
        .replace("},{", "}%,%{")
        .split("%,%")
    ]
    if settings_dict.get("tags", "None") != "None":
        settings_dict["tags"] = ["list"] + [
            json.loads(tag_json)
            for tag_json in settings_dict["tags"].replace("},{", "}%,%{").split("%,%")
        ]
    else:
        settings_dict["tags"] = ["list"] + [{"name": "", "icon": "", "sort_pos": ""}]
    settings_editor_html = render_template_string(
        """
        {% from 'main/settings-editor.html' import SettingsEditor with context %}
        {{ SettingsEditor() }}
        """,
        files_html=files_html,
        version=version,
        revision_number=revision_number,
        user_dicts=user_dicts,
        settings_dict=settings_dict,
        settings_doc_dict=settings_doc_dict,
        user_settings_doc_dict=user_settings_doc_dict,
        access_group=access_group,
        access_groups=access_groups,
        users=users,
    )
    backup_working_config()
    return settings_editor_html


@main.route("/app_view?<app_id>", methods=["GET"])
def app_view(app_id):
    access_group, redirect_url = get_access_group(current_user)
    apps, tags = get_apps_and_tags(access_group)
    if redirect_url:
        return redirect(redirect_url)
    app_db = Apps.query.filter_by(id=app_id).first()
    return render_template(
        "main/app-view.html",
        url=f"{app_db.prefix}{app_db.url}",
        title=app_db.name,
        access_group=access_group,
        apps=apps,
        tags=tags,
    )


@main.route("/load_data_source", methods=["GET"])
def load_data_source():
    data_source = DataSources.query.filter_by(id=request.args.get("id")).first()
    data = get_data_source(data_source)
    return data


@main.route("/update_message_read", methods=["GET"])
def update_message_read():
    mark_update_message_read()
    return "ok"


@main.route("/build_action_provider_url", methods=["GET"])
def build_action_provider_url():
    url = render_template_string(
        request.args.get("action"), value=request.args.get("value")
    )
    return url


@main.route("/get_card_editor_form", methods=["GET"])
def get_card_editor_form():
    app_templates = None
    if request.args.get("type", None) == "app":
        new_app = Apps(type="app")
        card = row2dict(new_app)
        app_templates = get_template_apps()

    elif request.args.get("type", None) == "collection":
        new_app = Apps(type="collection")
        card = row2dict(new_app)
        card["urls"] = '{"url": "", "icon": "", "name": "", "open_in": ""}'
    elif request.args.get("type", None) == "custom":
        new_app = Apps(type="custom")
        card = row2dict(new_app)
    else:
        card_db = Apps.query.filter_by(id=request.args.get("app_id")).first()
        card = row2dict(card_db)
        card["tags"] = ",".join([tag.name for tag in card_db.tags])
        card["groups"] = ",".join([group.name for group in card_db.access_groups])
        card["data_sources"] = ",".join([ds.name for ds in card_db.data_sources])

    if not card.get("tags", None):
        card["tags"] = ""
    if not card.get("groups", None):
        card["groups"] = ""
    if not card.get("data_sources", None):
        card["data_sources"] = ""

    if card["urls"] != "None":
        urls = card["urls"]
        del card["urls"]
        card["urls"] = ["list"] + [
            json.loads(url_json)
            for url_json in urls.replace("},{", "}%,%{").split("%,%")
        ]
    doc_dict = get_card_doc_dict(card["type"])
    if card["type"] == "app":
        anchor = "cards-apps"
    elif card["type"] == "collection":
        anchor = "cards-collection"
    elif card["type"] == "custom":
        anchor = "cards-custom"
    doc_dict["docs_url"] = url_for("docs_system.docs_cards", _anchor=anchor)
    form_html = render_template_string(
        """
        {% from 'main/ini-form.html' import INIForm %}
        {% if card['name'] != 'None' %}
            <h5 class="theme-primary-text">Editing {{ card['name'] }}</h5>
        {% else %}
            <h5 class="theme-primary-text">New {{ doc_dict['name'] }}</h5>
        {% endif %}
        {{ INIForm(card, doc_dict, location="card-editor", app_templates=app_templates) }}
        """,
        card=card,
        doc_dict=doc_dict,
        app_templates=app_templates,
    )
    return form_html


@main.route("/get_card_editor_ds_form", methods=["GET"])
def get_card_editor_ds_form():
    ds_selector = None

    if request.args.get("new", None) == "True":
        data_source = {}
        doc_dict = {}
        ds_selector = [ds["name"] for ds in data_sources_doc_dicts(get_all=True)]
    elif request.args.get("platform", None):
        doc_dict = data_sources_doc_dicts(platform_name=request.args.get("platform"))[0]
        for variable in doc_dict["variables"]:

dashmachine/user_system/routes.py
from flask import render_template, url_for, redirect, Blueprint, jsonify
from flask_login import login_user, logout_user
from dashmachine.user_system.forms import LoginForm
from dashmachine.user_system.models import User
from dashmachine import bcrypt
from dashmachine.main.utils import public_route

user_system = Blueprint("user_system", __name__)


# ------------------------------------------------------------------------------
# User system routes
# ------------------------------------------------------------------------------
# login page
@public_route
@user_system.route("/login", methods=["GET"])
def login():
    form = LoginForm()
    return render_template("user/login.html", title="Login", form=form)


@public_route
@user_system.route("/check_login", methods=["POST"])
def check_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data.lower()).first()
        if not user:
            response = {"err": "User not found"}

        elif bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            response = {"url": url_for("main.home")}
        else:
            response = {"err": "Password is wrong"}
    else:
        response = {"err": str(form.errors)}

    return jsonify(data=response)


# this logs the user out and redirects to the login page
@user_system.route("/logout")
def logout():

    logout_user()
    return redirect(url_for("user_system.login"))

dashmachine/templates/main/app-view.html
{% extends "main/layout.html" %}
{% block page_vendor_css %}
{% endblock page_vendor_css %}

{% block page_lvl_css %}
{% endblock page_lvl_css %}

{% block content %}
    <div id="main" class="main-full">
        <iframe src="{{ url }}" style="width: 100%; height: 100vh; border: 0">
        </iframe>
    </div>
    </div>
{% endblock content %}

{% block page_vendor_js %}
{% endblock page_vendor_js %}

{% block page_lvl_js %}

{% endblock page_lvl_js %}

dashmachine/templates/main/card-editor.html
{#  CARD EDITOR #}
{% macro CardEditor() %}
    <style>
        #card-editor-sidenav .card-editor-add-dropdown-overlay {
            position: absolute;
            background-color: rgba(0,0,0, 0.5);
            margin: -2%;
            top: 0;
            left: 0;
            height: 102vh;
            width: 104%;
        }
    </style>

    <div id="card-editor-cards-table" class="row">
        <div class="row card-filter-container">
            <div class="hide card-editor-add-dropdown-overlay"></div>
            <div class="col s12 input-field">
                <span>
                    <i class="material-icons prefix card-search-icon">search</i>
                    <input type="text" id="card-editor-card-search" class="card-filter theme-surface" placeholder="Search cards">
                    <a id="card-editor-add-btn" class='dropdown-trigger' href='#' data-target='card-editor-add-dropdown'>
                        <i class="material-icons right filter-action pointer">add</i>
                    </a>
                    <i class="material-icons right filter-action pointer show-card-editor-data-sources-table">language</i>
                </span>

                <ul id='card-editor-add-dropdown' class='dropdown-content' data-url="{{ url_for('main.get_card_editor_form') }}">
                    <li><a href="#" class="card-editor-add-dropdown-a" data-type="app">
                        <i class="material-icons-outlined">add</i>App
                    </a></li>
                    <li><a href="#" class="card-editor-add-dropdown-a" data-type="collection">
                        <i class="material-icons-outlined">add</i>Collection
                    </a></li>
                    <li><a href="#" class="card-editor-add-dropdown-a" data-type="custom">
                        <i class="material-icons-outlined">add</i>Custom Card
                    </a></li>
                    <li><a href="{{ url_for('docs_system.docs_cards') }}">
                        <i class="material-icons-outlined">info</i>Cards Docs
                    </a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <table class="highlight centered">
                    <thead class="mb-2">
                    <tr class="theme-on-primary-text font-weight-900" style="font-size: 1.1rem; border: 0">
                        <th class="theme-primary" style="border-radius: 10px 0 0 10px;">Name</th>
                        <th class="theme-primary" style="border-radius: 0;">Type</th>
                        <th class="theme-primary" style="border-radius: 0 10px 10px 0;">Tags</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for app in apps %}
                        <tr class="card-editor-app-row"
                            style="border: 0"
                            data-id="{{ app.id }}"
                            data-url="{{ url_for('main.get_card_editor_form') }}">
                            <td style="border-radius: 10px 0 0 10px;">{{ app.name }}</td>
                            <td style="border-radius: 0;">{{ app.type }}</td>
                            <td style="border-radius: 0 10px 10px 0;">
                                {% for tag in app.tags %}
                                    -{{ tag.name }}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="card-editor-data-sources-table" class="row hide">
        <div class="row card-filter-container">
            <div class="hide card-editor-add-dropdown-overlay"></div>
            <div class="col s12 input-field">
                <span>
                    <i class="material-icons prefix card-search-icon">search</i>
                    <input type="text" id="card-editor-data-sources-search" class="card-filter theme-surface" placeholder="Search data sources">

                    <a id="card-editor-data-source-add-btn" class='dropdown-trigger' href='#' data-target='card-editor-data-source-add-dropdown'>
                        <i class="material-icons right filter-action pointer">add</i>
                    </a>
                    <ul id='card-editor-data-source-add-dropdown' class='dropdown-content'>
                        <li><a href="#" id="card-editor-add-new-ds-btn" data-url="{{ url_for('main.get_card_editor_ds_form', new="True") }}">
                            <i class="material-icons-outlined">add</i>Data Source
                        </a></li>
                        <li><a href="{{ url_for('docs_system.docs_data_sources') }}">
                            <i class="material-icons-outlined">info</i>Data Source Docs
                        </a></li>
                    </ul>

                    <i class="material-icons right filter-action pointer show-card-editor-cards-table">aspect_ratio</i>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <table class="highlight centered">
                    <thead>
                    <tr>
                        <th class="theme-primary theme-on-primary-text" style="border-radius: 10px 0 0 10px;">Name</th>
                        <th class="theme-primary theme-on-primary-text" style="border-radius: 0 10px 10px 0;">Platform</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for ds in data_sources %}
                        <tr class="card-editor-data-source-row"
                            data-id="{{ ds['id'] }}"
                            data-url="{{ url_for('main.get_card_editor_ds_form') }}">
                            <td style="border-radius: 10px 0 0 10px;">{{ ds['name'] }}</td>
                            <td style="border-radius: 0 10px 10px 0;">{{ ds['platform'] }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="card-editor-form-container"></div>
    <div id="card-editor-data-sources-form-container"></div>

    {{ process_js_sources(src="main/card-editor.js")|safe }}
{% endmacro %}

dashmachine/templates/main/layout.html
{% extends "main/base.html" %}
{% from 'global_macros.html' import SidenavToggle, ActionBar %}
{% from 'main/cards.html' import SidenavApps %}

{% block header %}
    <!-- BEGIN: Header-->
    {% if access_group.can_see_sidenav == "True" %}
        <div id="sidenav-toggle" style="position: fixed; z-index: 8000">
            {{SidenavToggle()}}
        </div>
    {% else %}
        <div class="fixed-action-btn">
            <a href="{{ url_for('user_system.login') }}" class="btn-floating theme-primary">
                <i class="material-icons-outlined theme-on-primary-text">person</i>
            </a>
        </div>
    {% endif %}
    <!-- END: Header-->
{% endblock header %}

{% block sidenav %}
    <div id="card-editor-sidenav" class="sidenav z-depth-4 theme-background">
        <div class="row padding-2">
            <div class="col s12">
                <div id="card-editor-container" data-url="{{ url_for('main.load_card_editor') }}">
                    <div class="progress">
                        <div class="indeterminate"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="config-editor-sidenav" class="sidenav z-depth-4 theme-background">
        <div class="row padding-2">
            <div class="col s12">
                <div id="config-editor-container" data-url="{{ url_for('main.load_config_editor') }}">
                    <div class="progress">
                        <div class="indeterminate"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="settings-editor-sidenav" class="sidenav z-depth-4 theme-background">
        <div class="row padding-2">
            <div class="col s12">
                <div id="settings-editor-container" data-url="{{ url_for('main.load_settings_editor') }}">
                    <div class="progress">
                        <div class="indeterminate"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="main-sidenav" class="sidenav theme-background z-depth-5" style="z-index: 8001">
        <div class="row mt-2 mr-2 ml-2">
            {% if current_user %}
                <span id="toggle-user-theme-btn" data-url="{{ url_for('main.toggle_theme') }}" data-user_id="{{ current_user.id }}">
                    {% if current_user.theme %}
                        {% if current_user.theme == "light" %}
                            <i class="material-icons-outlined icon-btn theme-secondary-text">toggle_off</i>
                        {% elif current_user.theme == "dark" %}
                            <i class="material-icons-outlined icon-btn theme-primary-text">toggle_on</i>
                        {% endif %}
                    {% else %}
                        {% if settings.theme == "light" %}
                            <i class="material-icons-outlined icon-btn theme-secondary-text">toggle_off</i>
                        {% elif settings.theme == "dark" %}
                            <i class="material-icons-outlined icon-btn theme-primary-text">toggle_on</i>
                        {% endif %}
                    {% endif %}
                </span>
            {% endif %}

            {% if page != "home" %}
                <a href="{{ url_for('main.home') }}">
                    <i class="material-icons-outlined icon-btn right">dashboard</i>
                </a>
            {% endif %}

            {% if access_group.can_access_user_settings == "True" or access_group.can_access_main_settings == "True" or access_group.can_edit_images == "True" %}
                <a id="settings-editor-open-btn" href="#"  data-target="settings-editor-sidenav" class="sidenav-trigger">
                    <i class="material-icons-outlined icon-btn right">settings</i>
                </a>
            {% endif %}

            {% if access_group.can_access_card_editor == "True"%}
                <a id="card-editor-open-btn" href="#"  data-target="card-editor-sidenav" class="sidenav-trigger">
                    <i class="material-icons-outlined icon-btn right">aspect_ratio</i>
                </a>
            {% endif %}

            {% if access_group.can_access_raw_config == "True"%}
                <a id="config-editor-open-btn" href="#"  data-target="config-editor-sidenav" class="sidenav-trigger">
                    <i class="material-icons-outlined icon-btn right">description</i>
                </a>
            {% endif %}

            {% if access_group.can_access_docs == "True" %}
                <a href="{{ url_for('docs_system.docs_home') }}">
                    <i class="material-icons-outlined icon-btn right">info</i>
                </a>
            {% endif %}

            {% if current_user.is_authenticated %}
                <a href="{{ url_for('user_system.logout') }}">
                    <i class="material-icons-outlined icon-btn right">exit_to_app</i>
                </a>
            {% else %}
                <a href="{{ url_for('user_system.login') }}">
                    <i class="material-icons-outlined icon-btn right">account_circle</i>
                </a>
            {% endif %}
        </div>
        <div class="divider"></div>

        {{ ActionBar(tags, location="sidenav") }}

        <div class="row">
            <div id="sidenav-cards-container"
                 data-url="{{ url_for('main.load_apps', sidenav="true") }}"
                 class="col s12">
                {{ SidenavApps(apps, tags) }}
            </div>
        </div>
    </div>
    <!-- END: SideNav-->

{% endblock sidenav%}

{% block modules %}
    <script>
        $( document ).ready(function() {
            load_card_editor();
            load_config_editor();
            load_settings_editor();
        });
    </script>
{% endblock modules %}

{% block footer %}
    <!-- BEGIN: Footer-->
    <!-- <footer class="page-footer footer footer-static footer-light navbar-border navbar-shadow">
      <div class="footer-copyright">
        <div class="container"><span>&copy; 2019 All rights reserved.</span><span class="right hide-on-small-only">DashMachine</span></div>
      </div>
    </footer> -->
    <!-- END: Footer-->
{% endblock footer %}